import { DollarSign, ShoppingCart, Users, TrendingUp, Briefcase, Target, Cpu, Shield, Zap, Globe, Heart, Clock, Activity, Brain } from 'lucide-react';
import { Department, KPIData, WidgetConfig } from '../types/dashboard';

export const DEPT_DATA: Record<Department, { kpis: KPIData[], widgets: WidgetConfig[] }> = {
  Sales: {
    kpis: [
      { title: 'Total Revenue', value: '$4.2M', trend: '+12.5%', trendType: 'up', icon: DollarSign },
      { title: 'Win Rate', value: '64%', trend: '+4.2%', trendType: 'up', icon: Target },
      { title: 'Avg Deal Size', value: '$24.5k', trend: '+1.2%', trendType: 'up', icon: Briefcase },
      { title: 'Sales Cycle', value: '18 Days', trend: '-2 Days', trendType: 'up', icon: Clock },
    ],
    widgets: [
      {
        id: 'revenue-by-month',
        type: 'area',
        title: 'Revenue Momentum',
        description: 'Monthly recurring revenue growth with 3-month forecast.',
        data: [
          { month: 'Jan', revenue: 240000, target: 220000 },
          { month: 'Feb', revenue: 280000, target: 250000 },
          { month: 'Mar', revenue: 320000, target: 300000 },
          { month: 'Apr', revenue: 310000, target: 350000 },
          { month: 'May', revenue: 380000, target: 400000 },
          { month: 'Jun', revenue: 450000, target: 450000 },
          { month: 'Jul', revenue: 520000, target: 500000, forecast: true },
          { month: 'Aug', revenue: 580000, target: 550000, forecast: true },
        ],
        dataKey: ['revenue', 'target'],
        categoryKey: 'month',
        gridSpan: 8,
        forecast: true,
        colors: ['#6366f1', '#10b981']
      },
      {
        id: 'sales-by-region',
        type: 'pie',
        title: 'Regional Performance',
        description: 'Revenue distribution across global territories.',
        data: [
          { region: 'North America', revenue: 45 },
          { region: 'Europe', revenue: 25 },
          { region: 'Asia Pacific', revenue: 20 },
          { region: 'Latin America', revenue: 10 },
        ],
        dataKey: 'revenue',
        categoryKey: 'region',
        gridSpan: 4,
        colors: ['#6366f1', '#8b5cf6', '#ec4899', '#f59e0b']
      },
      {
        id: 'lead-conversion',
        type: 'bar',
        title: 'Lead Conversion Pipeline',
        description: 'Stage-by-stage breakdown of sales opportunities.',
        data: [
          { stage: 'Prospecting', count: 1200 },
          { stage: 'Discovery', count: 850 },
          { stage: 'Proposal', count: 420 },
          { stage: 'Negotiation', count: 210 },
          { stage: 'Closed', count: 145 },
        ],
        dataKey: 'count',
        categoryKey: 'stage',
        gridSpan: 6,
        colors: ['#6366f1']
      },
      {
        id: 'rep-performance',
        type: 'stacked-bar',
        title: 'Top Performers',
        description: 'Revenue generated by individual account executives.',
        data: [
          { name: 'Sarah J.', quota: 120000, actual: 145000 },
          { name: 'Michael C.', quota: 100000, actual: 98000 },
          { name: 'Elena R.', quota: 150000, actual: 162000 },
          { name: 'David W.', quota: 80000, actual: 110000 },
        ],
        dataKey: ['quota', 'actual'],
        categoryKey: 'name',
        gridSpan: 6,
        colors: ['#ffffff10', '#6366f1']
      }
    ]
  },
  HR: {
    kpis: [
      { title: 'Headcount', value: '1,240', trend: '+45', trendType: 'up', icon: Users },
      { title: 'Retention', value: '94%', trend: '+2%', trendType: 'up', icon: Heart },
      { title: 'eNPS', value: '72', trend: '+5', trendType: 'up', icon: Zap },
      { title: 'Avg Tenure', value: '3.2 yrs', trend: '+0.4', trendType: 'up', icon: Clock },
    ],
    widgets: [
      {
        id: 'hr-growth',
        type: 'line',
        title: 'Workforce Growth',
        description: 'Employee headcount trends over the last 12 months.',
        data: [
          { month: 'Jan', count: 1100 },
          { month: 'Feb', count: 1120 },
          { month: 'Mar', count: 1150 },
          { month: 'Apr', count: 1180 },
          { month: 'May', count: 1200 },
          { month: 'Jun', count: 1240 },
        ],
        dataKey: 'count',
        categoryKey: 'month',
        gridSpan: 7,
        colors: ['#ec4899']
      },
      {
        id: 'diversity',
        type: 'pie',
        title: 'Diversity & Inclusion',
        description: 'Workforce distribution by department.',
        data: [
          { dept: 'Engineering', count: 450 },
          { dept: 'Sales', count: 320 },
          { dept: 'Marketing', count: 180 },
          { dept: 'Ops', count: 290 },
        ],
        dataKey: 'count',
        categoryKey: 'dept',
        gridSpan: 5,
        colors: ['#6366f1', '#10b981', '#f59e0b', '#ec4899']
      }
    ]
  },
  IT: {
    kpis: [
      { title: 'Uptime', value: '99.99%', trend: '+0.01%', trendType: 'up', icon: Activity },
      { title: 'Security Score', value: 'A+', trend: 'Stable', trendType: 'up', icon: Shield },
      { title: 'MTTR', value: '42m', trend: '-15m', trendType: 'up', icon: Clock },
      { title: 'Active Servers', value: '842', trend: '+12', trendType: 'up', icon: Cpu },
    ],
    widgets: [
      {
        id: 'infra-load',
        type: 'area',
        title: 'System Load',
        description: 'CPU and Memory utilization across the global cluster.',
        data: [
          { time: '00:00', cpu: 45, mem: 62 },
          { time: '04:00', cpu: 32, mem: 48 },
          { time: '08:00', cpu: 85, mem: 71 },
          { time: '12:00', cpu: 78, mem: 92 },
          { time: '16:00', cpu: 62, mem: 84 },
          { time: '20:00', cpu: 48, mem: 65 },
        ],
        dataKey: ['cpu', 'mem'],
        categoryKey: 'time',
        gridSpan: 12,
        colors: ['#06b6d4', '#8b5cf6']
      }
    ]
  },
  Marketing: {
    kpis: [
      { title: 'CPL', value: '$12.40', trend: '-$1.20', trendType: 'up', icon: Target },
      { title: 'CTR', value: '4.8%', trend: '+0.5%', trendType: 'up', icon: MousePointer2 },
      { title: 'ROAS', value: '5.2x', trend: '+0.4x', trendType: 'up', icon: TrendingUp },
      { title: 'Ad Spend', value: '$145k', trend: '+12k', trendType: 'down', icon: DollarSign },
    ],
    widgets: []
  },
  SaaS: {
    kpis: [
      { title: 'MRR', value: '$840k', trend: '+12%', trendType: 'up', icon: DollarSign },
      { title: 'Churn', value: '1.2%', trend: '-0.2%', trendType: 'up', icon: TrendingUp },
      { title: 'ARPU', value: '$145', trend: '+$5', trendType: 'up', icon: User },
      { title: 'LTV', value: '$12.4k', trend: '+$1k', trendType: 'up', icon: Briefcase },
    ],
    widgets: []
  },
  Product: {
    kpis: [
      { title: 'MAU', value: '1.2M', trend: '+8%', trendType: 'up', icon: Users },
      { title: 'DAU/MAU', value: '42%', trend: '+2%', trendType: 'up', icon: Activity },
      { title: 'NPS', value: '64', trend: '+4', trendType: 'up', icon: Heart },
      { title: 'Crash Rate', value: '0.04%', trend: '-0.01%', trendType: 'up', icon: Shield },
    ],
    widgets: []
  },
  AI: {
    kpis: [
      { title: 'Inference', value: '4.2M', trend: '+24%', trendType: 'up', icon: Brain },
      { title: 'Latency', value: '124ms', trend: '-12ms', trendType: 'up', icon: Zap },
      { title: 'Token Cost', value: '$0.02', trend: '-$0.01', trendType: 'up', icon: DollarSign },
      { title: 'Accuracy', value: '98.2%', trend: '+0.5%', trendType: 'up', icon: Target },
    ],
    widgets: []
  },
  Operations: {
    kpis: [
      { title: 'Efficiency', value: '94%', trend: '+2%', trendType: 'up', icon: Zap },
      { title: 'Backlog', value: '12', trend: '-4', trendType: 'up', icon: Clock },
      { title: 'Region Coverage', value: '18', trend: '+2', trendType: 'up', icon: Globe },
      { title: 'Safety Incidents', value: '0', trend: 'Stable', trendType: 'up', icon: Shield },
    ],
    widgets: []
  }
};

// Add some missing icon imports if needed
import { MousePointer2, User } from 'lucide-react';
